### ISSUE TITLE
Edit field of module designer not working on 1 of 2 vtiger sites.

### ISSUE THREAD

**Issue by lorijn** [sardoj/VTModuleDesigner#24]
Hello Jonathon,

First many thanks for creating this module !

I have module designer installed on 2 vtiger websites.
On 1 server the edit of a module field is working ok, on 1 it's not working ok.

Firebug NET panel gives an network error on "GET CustomScript.js" ->
"NetworkError: 404 Not Found - 'myurl'/modules/Settings/ModuleDesigner/js/CustomScript.js"

{"success":false,"error":{"code":"error-param","message":"LBL_ERROR_PARAM"}

I'll hope you gan give me some help how to solve this issue ?

Kind regards,

Marc

**Comment by sardoj** [comment]
Hello,

Module Designer does not work with magic_quote_gpc().
Maybe is it activated on website 2?

**Comment by lorijn** [comment]
Hello Jonathon,

## phpinfo gives it's Off on both servers.

magic_quotes_gpc    Off
magic_quotes_runtime    Off
magic_quotes_sybase Off

## (json is enabled on both servers)

So, this is a weird problem.
The add of a field is working fine, only the edit of a field gives a blanco popup.

Is the GET of CustomScript.js involved with the edit of a field ?

Kind regards,

Marc

**Comment by sardoj** [comment]
Ok !

Did you applied the Vtiger path (given in github)?

**Comment by lorijn** [comment]
Yes, i have applied the patch on both servers.

**Comment by sardoj** [comment]
Ok so i don't know. Sorry.
Please share with us if you find a solution.

**Comment by lorijn** [comment]
Yes, ok. (no problem, thanks for the quick respons)

**Comment by playmono** [comment]
Hi,

I think with the last commit this should be fixed, can you check it? I'll mark as close if no response in a week.

Thanks!

**Comment by juanlanzagortafv** [comment]
{"success":false,"error":{"code":"error-param","message":"LBL_ERROR_PARAM"}}

Same error here... I already downloaded the GitHub las files, installed them and it is the same answer... I can create fields but not edit them

**Comment by sardoj** [comment]
Thanks for your answer. Actually there is a problem with URL parameters
which are not passed....weird...
Maybe do you have a problem with json on your computer?

**Comment by brundles** [comment]
I still have this "LBL_ERROR_PARAM" on all fields i try to edit. Meaning i can use the module, but i have to "get each field right first time" or i cannot edit them :-/

**Comment by brundles** [comment]
Hi @sardoj and @playmono 

This is very sad which such a brilliant module - so i've debugged the matter further, and it seems that its failing in "EditField.php" on line 32 around:
`		if((!$request->get("field") && !$request->get("uitype")) || !$request->get("mod") || !$request->get("languages"))
		{
			//Make JSON response	`

Main issue seems that it is not getting the field from the frontend.

I've included both the clean and url-encoded request here:

`module:ModuleDesigner
view:EditField
mod:Addresses
exist:1
field:{"id":"md-field-0-0","index":1,"UITypeNum":16,"UITypeDataType":"V","UITypeDBType":"VARCHAR(128)","fieldName":"type","label":"LBL_TYPE","tableName":"vtiger_addresses","columnName":"type","helpInfoLabel":"What type of address is this?","defaultValue":"Company","generatedType":1,"displayType":1,"mandatory":1,"isEntityIdentifier":false,"entityIdentifierFieldName":"","quickCreate":false,"massEditable":true,"readOnly":false,"pickListValues":"Company,Shipping,Invoice,Other","UITypeName":"Pick list","inFilterAll":true,"label_en_us":"Type","helpInfoLabel_en_us":"What type of address is this?","label_fr_fr":"Type","helpInfoLabel_fr_fr":"What type of address is this?","inPopup":true,"popupSequence":5,"inRelatedList":true,"relatedListSequence":1,"MDEditable":true}
languages:en_us,fr_fr
parent:Settings`


And URL-encoded:

`%7B%22id%22%3A%22md-field-0-0%22%2C%22index%22%3A1%2C%22UITypeNum%22%3A16%2C%22UITypeDataType%22%3A%22V%22%2C%22UITypeDBType%22%3A%22VARCHAR%28128%29%22%2C%22fieldName%22%3A%22type%22%2C%22label%22%3A%22LBL_TYPE%22%2C%22tableName%22%3A%22vtiger_addresses%22%2C%22columnName%22%3A%22type%22%2C%22helpInfoLabel%22%3A%22What%20type%20of%20address%20is%20this%3F%22%2C%22defaultValue%22%3A%22Company%22%2C%22generatedType%22%3A1%2C%22displayType%22%3A1%2C%22mandatory%22%3A1%2C%22isEntityIdentifier%22%3Afalse%2C%22entityIdentifierFieldName%22%3A%22%22%2C%22quickCreate%22%3Afalse%2C%22massEditable%22%3Atrue%2C%22readOnly%22%3Afalse%2C%22pickListValues%22%3A%22Company%2CShipping%2CInvoice%2COther%22%2C%22UITypeName%22%3A%22Pick%20list%22%2C%22inFilterAll%22%3Atrue%2C%22label_en_us%22%3A%22Type%22%2C%22helpInfoLabel_en_us%22%3A%22What%20type%20of%20address%20is%20this%3F%22%2C%22label_fr_fr%22%3A%22Type%22%2C%22helpInfoLabel_fr_fr%22%3A%22What%20type%20of%20address%20is%20this%3F%22%2C%22inPopup%22%3Atrue%2C%22popupSequence%22%3A5%2C%22inRelatedList%22%3Atrue%2C%22relatedListSequence%22%3A1%2C%22MDEditable%22%3Atrue%7D`

Ie. there is the JSON formatted field-variable sent to the server, but somehow its not understood correctly. Any ideas?
